# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

 

variables: { system.debug: 'true' }

 

trigger:
- master
stages:
  - stage: UTStage1
    jobs:
    - job: UTJob1
      pool:
        name: Default
        demands:
        - msbuild
        - visualstudio
        - vstest
      variables:
        solution: '**/*.sln'
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'
      steps:
      - script: SET  
      - task: PublishTestResults@2
        displayName: 'Publish Test Results test-all.trx'
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: 'largetests.trx.trx'
          searchFolder: 'D:\AbortedProj'